development:
  adapter: postgresql
  encoding: unicode
  database: planting_season_coordinator_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: planting_season_coordinator_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: planting_season_coordinator_production
  pool: 5
  username:
  password:
